### ISSUE TITLE
Replace NaN values

### ISSUE THREAD

**Issue by mmaelicke** [KIT-HYD/bridget#4]
### Problem
Our Test data seems to contain numeric substitutes for NaN values. E.g. with one of the testfiles:

```python
from bridget.io import read_TK2_file
df = read_TK2_file('./data/Fendt_TK2_result_2014.csv')
df.CO2.where(df.CO2 < 0).dropna()
```
yields:
![image](https://user-images.githubusercontent.com/2826034/80352150-bbb46600-8873-11ea-84d7-864f74fdcbaa.png)

and the plot of the time series looks like:

![image](https://user-images.githubusercontent.com/2826034/80352236-dc7cbb80-8873-11ea-9faa-d51859bc1a63.png)

### Suggestion

We should verify, that this is actually a NaN (@sihassl ?) and check the other files and variables for other values (@AlexDo1 ). Is it always the same?
Then we need to implement this as a default NaN value option to convert it properly to `numpy.NaN`.

**Comment by mmaelicke** [comment]
Could confirm these are NaNs. @AlexDo1, you can now check the other columns and files, if always the **exact** value is used.

**Comment by AlexDo1** [comment]
Okay I'll do that and I guess that I will also replace the -9999 values with numpy.NaN values.

**Comment by AlexDo1** [comment]
It looks like -9999.9003906 is unique for these NaN values (at least in the column CO2), but there are different negative values for CO2, which should be wrong, but I guess these values shouldn´t be replaced with NaN.

![image](https://user-images.githubusercontent.com/23619690/80369352-6cc7fa00-888e-11ea-8501-7d7861a0f199.png)

**Comment by mmaelicke** [comment]
Yes, following the header-file the unit is [mmol/m³]. I would guess this is not a concentration, but a flux. So, + and - is direction, which I would guess is upward (+) and downward (-).

Just to be clear: The `-9999.9003906` should **not** be replaced in the sample files, but rather set in the `read_*_file` function as a default value for nan like:
```python
def read_TK2_file(fname, strict=True, na_values=-9999.9003906):
    [...]
```

Then passed to the `pandas.read_csv` function. The correct argument name shoudl be `na_values` can be found in their docs: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

**Comment by AlexDo1** [comment]
Okay, I did that on the sample data :/
But at least the plotted data looks good when replacing -9999.9003906 with NaN.

I´ll look into the read_TK2_file function now.

**Comment by mmaelicke** [comment]
I think the only issue we could run into is, when a whole coulmn is NaN only. Then it's removed during data import and the merging with default column names will not work anymore, because of shape mismatch. We should test this....
