### ISSUE TITLE
DateTime columns are not of type DateType automatically

### ISSUE THREAD

**Issue by AlexDo1** [KIT-HYD/bridget#7]
When reading in the TK2 files, the DateTime columns (t_begin, t_end, t_mid) are not of type DateTime.

![image](https://user-images.githubusercontent.com/23619690/80714817-c0884c80-8af5-11ea-9b05-a6f78971f013.png)

The columns need to be adjusted to DateTime by hand (also necessary to plot data over time):

![image](https://user-images.githubusercontent.com/23619690/80714959-f4fc0880-8af5-11ea-828f-4a40d1aacf7c.png)

---
Should I add this code to the _reader function?

**Comment by mmaelicke** [comment]
Yeah, good idea. You can add this on the open PR and I will link this issue to it
